name: Deploy WordPress Theme via FTP

on:
  push:
    branches:
      - main # lub 'master', w zależności od nazwy Twojej głównej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-dev --working-dir=./ting-tong-theme/

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ting-tong-theme/
        server-dir: /autoinstalator/wordpresspluslscache2/wp-content/themes/ting-tong-theme/
        protocol: ftp
        port: 21
        timeout: 30000
        log-level: "verbose"
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/**
          # Usunięto 'vendor/**' z tej listy, aby umożliwić wgranie
