name: Deploy WordPress Theme via FTP

on:
  push:
    branches:
      - main # lub 'master', w zależności od nazwy Twojej głównej gałęzi

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # KRYTYCZNY KROK: Tworzy plik .env z kluczami Stripe w katalogu motywu
    - name: Create .env file for Stripe keys
      run: |
        echo "Secret_key=${{ secrets.SECRET_KEY }}" > ting-tong-theme/.env
        echo "Publishable_key=${{ secrets.PUBLISHABLE_KEY }}" >> ting-tong-theme/.env

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./ting-tong-theme/
        server-dir: /autoinstalator/wordpresspluslscache2/wp-content/themes/ting-tong-theme/
        protocol: ftp
        port: 21
        timeout: 30000
        log-level: "verbose"
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          .github/**